### ISSUE TITLE
Website hackaton

### ISSUE THREAD

**Issue by tdido** [cnio-bu/website#12]
The idea is to use a Tech Lab Meeting to work on sections of the website in groups (pairs or so).

**Comment by SGMartin** [comment]
Any examples?

**Comment by tdido** [comment]
Your "publications" page I suppose ;)

**Comment by FranSoriano** [comment]
I leave you here the presentation of the lab meeting in case you need to consult something :):

[TechLabMeeting-Hackathon.pdf](https://github.com/cnio-bu/website/files/10782884/TechLabMeeting-Hackathon.pdf)
