### ISSUE TITLE
Add "Publications" page

### ISSUE THREAD

**Issue by SGMartin** [cnio-bu/website#2]
I'll fill this once I exit the lab. meeting. Leaving this to remind myself.

**Comment by SGMartin** [comment]
I've been researching the template and I guess the best way to organize the publications page is to follow the "about" template, which features a side menu which could be sorted from current year to oldest (circa 2017).

**Comment by SGMartin** [comment]
The old website added publications as a sorted list. See an example [here](https://bioinformatics.cnio.es/publications/). I guess we could keep reporting the publications this way. However, before going forward, I'd like some feedback from @mj-jimenez and @laumtnezg. Any ideas for a fresh way to report publications?

**Comment by mj-jimenez** [comment]
I think we can add color labels with different topics, which can be hierarchical (i.e. tools > genomics > pandrugs). Also it would be great to allow visitors to filter by this label across all years.

**Comment by laumtnezg** [comment]
> I think we can add color labels with different topics, which can be hierarchical (i.e. tools > genomics > pandrugs). Also it would be great to allow visitors to filter by this label across all years.

That sounds great! 

One thing I think we could change from the old one is to just use bold text for the authors (instead of blue color) because it looks like there's a hyper link to the authors orcid or list of publications. Or we could just redirect to this person's info page.

**Comment by tdido** [comment]
Closed via #11
