### ISSUE TITLE
Some publication years have the authors before the title

### ISSUE THREAD

**Issue by tdido** [cnio-bu/website#20]
2018 and earlier to be specific

https://cnio-bu.github.io/website/publications/2018/

**Comment by SGMartin** [comment]
Yeah, I started tracking pubs in 2020 so that explains It. Will fix It ASAP

**Comment by tdido** [comment]
Hello @SGMartin @FranSoriano, is this one fixed with the latest changes?

**Comment by FranSoriano** [comment]
Hello @tdido. Yes, this issue has been solved. I am closing it.

**Comment by FranSoriano** [comment]
This issue has been resolved with the latest modifications. Now, in each publication, the title appears first, followed by the authors.
